

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1)
R = PolynomialRing(GF(_sage_const_7 ), names=('x', 'y', 'z', 't',)); (x, y, z, t,) = R._first_ngens(4)
f1 = t*x**_sage_const_2 +x*y+z**_sage_const_3 +z
f2 = x**_sage_const_2 +x*y+_sage_const_3 *z**_sage_const_2 *t+z
print(f1.parent())
f1 = f1.subs(x=_sage_const_3 )
f1 = f1.subs(y=_sage_const_2 )
f2 = f2.subs(x=_sage_const_1 )
f2 = f2.subs(y=_sage_const_2 )
F = Sequence([f1,f2])
print(type(F))
print(F.reduced())

